[package]
name = "minijinja-cabi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
minijinja = { version = "2.0.2", path = "../minijinja", features = ["loader", "custom_syntax"] }
